---
# config/config.yaml
#
# please use https://direnv.net/ or similar to manage the environment variables

telegram:
  bot_token: "1111111111:XXXXX-XX-XXXXXXXXXXXXXX-XXX_XXXXXXX" # https://core.telegram.org/bots/tutorial
  chat_id: "-1111111111111"
  authorized_users:
    - 1111111111
  enable_message_forwarding: False # forward messages from telegram to the meshtastic network
  use_topics: False # map meshtastic channels to different topics in Telegram

meshtastic:
  connection_type: 'serial'  # 'serial' or 'tcp'
  device: "/dev/ttyACM0" # for serial connection
  node_info_link: "https://meshmap.net/#{node_id}" # link to node info page, {node_id} will be replaced with the actual node id
  # node_info_link: "https://malla.varna.radio/node/{node_id}" # link to node info page, {node_id} will be replaced with the actual node id
  #device: "192.168.0.100:4403" # for serial connection
  #default_node_id: '!da73e1bc'
  default_node_id: '^all' # where to send the telegram messages
  #default_channel_id: 0 # meshtastic channel send the telegram messages to
  #ignored_channels: # channels to ignore (do not send them to telegram)
  #  - 0
  #  - 1
  #  - 2
  heartbeat_timeout: 300 # timeout in seconds for node heartbeats
  commands:
    ping: True # /ping command to get your hop count and node id back
  #local_nodes:
  #  - '!ba66fc64'

# Name the channels
channels:
  - 'LongFast'
  - 'Bulgaria'

reports:
  telemetry: True
  location: False
  nodes: True

# set the message_thread_id for each topic
# read this https://stackoverflow.com/a/75178418/420585 to learn how to get the message_thread_id
topics:
  telemetry: 907
  location: 909
  nodes: 918
  channel0: 914
  channel1: 911

logging:
  level: 'info'
  level_telegram: 'warn'
  level_httpx: 'warn'
  use_syslog: false
  syslog_host: "127.0.0.1"
  syslog_port: 514
  syslog_protocol: 'udp'  # 'udp' or 'tcp'

